// File automatically generated by `vite-plugin-module-list`
export default [
  { path: "A.tsx", module: () => import("./pages/A.tsx") },
  { path: "B.tsx", module: () => import("./pages/B.tsx") },
  { path: "C.tsx", module: () => import("./pages/C.tsx") },
];
