// File automatically generated by `vite-plugin-module-list`
export default [
  { path: "A.tsx", module: () => import("./pages/A") },
  { path: "B.tsx", module: () => import("./pages/B") },
  { path: "C.tsx", module: () => import("./pages/C") },
];
