// File automatically generated by `vite-plugin-module-list`
export default [
  { path: "pages/A", module: () => import("./pages/A") },
  { path: "pages/B", module: () => import("./pages/B") },
  { path: "pages/C", module: () => import("./pages/C") },
  { path: "pages/section/D", module: () => import("./pages/section/D") },
];
